### PR TITLE
Expand reader tests

### PR DESCRIPTION
**Pull request by cc-a**
# Description

As prepatory work for #332 this PR expands the tests for the reader functions in `readers/csv.py` to more strictly codify the expected output. So far I've only looked at `tests/test_readers.py::test_read_trade_technodata` and wanted to get initial feedback before working on others. Particularly interested on anything else about the structure of the dataset that could be checked.

## Type of change

Please add a line in the relevant section of
[CHANGELOG.md](https://github.com/SGIModel/StarMuse/blob/development/CHANGELOG.md) to
document the change (include PR #) - note reverse order of PR #s.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (non-breaking, back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (whatever its nature)

## Key checklist

- [ ] All tests pass: `$ python -m pytest`
- [ ] The documentation builds and looks OK: `$ python -m sphinx -b html docs docs/build`

## Further checks

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Comment by tsmbland** [comment]
This looks good! I don't think there's anything else that needs to be checked

I've realised I don't actually know what the `TradeTechnodata.csv` file is for as it isn't included in the `default` example which is what I've been working off, so the data for this specific example probably isn't included in the schema for the new files. You'll want to base future functions off the `default` model (i.e. `copy_model("default", tmp_path)`) where possible.

In theory #312 is done, but I'll leave it up until after the standup tomorrow in case anyone else wants to review it. It would also be easy just to pin the numpy version in this PR or a separate one.

**Review by tsmbland — APPROVED** [review]

**Comment by cc-a** [comment]
This PR attempts attempts a comprehensive pass at the reader functions in an attempt to more rigourously define the data model used within Muse. Where possible reader functions are tested against the default example model using a single example data file. Other models are used where necessary. Some functions it was not possible/necessary to test for the reason given.

Reader functions tested against default model (and the data file used):
- read_technodictionary - "technodata/residential/Technodata.csv"
- read_io_technodata - "technodata/residential/CommOut.csv"
- read_initial_assets - "technodata/residential/ExistingCapacity.csv"
- read_global_commodities - "input/GlobalCommodities.csv"
- read_csv_agent_parameters - "technodata/Agents.csv"
- read_initial_market -  "input/Projections.csv"
- test_read_attribute_table - "input/Projections.csv"

Reader functions tested against other models:
- read_technodata_timeslices - default_timeslice - "technodata/power/TechnodataTimeslices.csv"

Reader funtions not tested:
- read_initial_capacity - called from multiple examples but is always passed an array and never reads data from a file
- read_technologies - wraps other reader functions, does not read data directly
- read_csv_timeslices - not called by any example model
- read_timeslice_shares - not called by any example model
- read_macro_drivers - not called by any example

Potentially these last may need to be reviewed as to whether they are still relevant or could be removed.

**Comment by cc-a** [comment]
Thanks @tsmbland. You make a good point. I think for your current purposes recording the tightest possible type makes sense particularly as it's hard to know how interchangeable e.g. ints and floats are in the code. But we should think carefully about how we tightly we specify types when writing tests for the planned changes.

**Review by tsmbland — APPROVED** [review]
Looks good! I think we can merge what you've got here and create a separate branch for the new inputs

**Pull request merged**
