### PR TITLE
Run notebooks as tests

### LINKED ISSUE #176: Run notebooks as tests
The documentation also uses numerous notebooks and it is important they are up-to date and work as expected with the code. A description on how to run notebooks as tests can be found: https://www.blog.pythonlibrary.org/2018/10/16/testing-jupyter-notebooks/

The is a `mark.notebook` available (see #165) but it is not used.

### PR DESCRIPTION
**Pull request by dalonsoa**
# Description

Builds on #173 and therefore needs to be review and merge after it. 

Runs all notebooks in the documentation as tests, so if any of them has any error, it will be flagged immediately. Bear in mind that these don't check if the output is correct, just if there are errors when running. The output might be plainly wrong. 

Together with #175 and #177 , this PR will ensure that documentation and examples are always up-to-date with the code.

Currently, tests are failing precisely because there are two notebooks that have errors (in particular, trying to run/load files that do not exist). 

Fixes #176

## Type of change

Please add a line in the relevant section of
[CHANGELOG.md](https://github.com/SGIModel/StarMuse/blob/development/CHANGELOG.md) to
document the change (include PR #) - note reverse order of PR #s.

- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (non-breaking, back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (whatever its nature)

## Key checklist

- [ ] All tests pass: `$ python -m pytest`
- [x] The documentation builds and looks OK: `$ python -m sphinx -b html docs docs/build`

## Further checks

- [x] Code is commented, particularly in hard-to-understand areas
- [x] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Review by sgiarols — APPROVED** [review]

**Review by sgiarols — APPROVED** [review]

**Review by sgiarols — COMMENTED** [review]
We can't merge this until we solve #217 because we would not be able to build the documentation

**Comment by dalonsoa** [comment]
@sgiarols , I've made some changes that reduce the number of failing tests, but I haven't got time to fix all. Here you have the changes I've made:

- The CI workflows now run directly `pytest tests/test_fullsim_regression.py` to avoid the artefact with failing tutorials.
- Some notebooks were failing because they were trying to load data that was not there for visualisation purposes. They were not part of the documentation, just a visualisation tool, so I've just remove the cells where that was happening. 
- I've removed the notebook related to trade altogether.

But, there are some missing bits:
- `docs/advanced-guide/further-extending-muse.ipynb` is trying to use a tutorial that do not exist at all. I don't see an easy fix but removing this part of the documentation altogether, which is a pity because it is a rather complete notebook. 
- `docs/tutorial-code/7-min-max-timeslice-constraints/2-max-constraint/visualise-max-service.ipynb` and `docs/user-guide/min-max-timeslice-constraints.ipynb` are both trying to plot things accessing a column (`supply`) that do not exist in the data (`Results/Power/Supply_Timeslice/2025.csv`).
- `docs/user-guide/add-gdp-correlation-demand.ipynb` is trying to access the results of a tutorial that do not exist: `tutorial-code/5-add-service-demand/2-correlation-demand`
- `docs/user-guide/addition-service-demand.ipynb` is also trying to access the results of a tutorial that do not exist: `tutorial-code/5-add-service-demand/1-exogenous-demand`

I'm sorry I cannot do more, now. We keep in touch.

**Comment by dalonsoa** [comment]
@sgiarols , has there been any progress with this?

**Comment by sgiarols** [comment]
@dalonsoa I am left with only one error from "/MUSE_OS/MUSE_OS/docs/advanced-guide/further-extending-muse.ipynb". It seems not to be able to locate the file "settings.toml". However, locally this is not happening. Can you take a look at this?

**Pull request merged**
