### PR TITLE
Update demand_share.py _inner_split function to solve reoccuring error message when running MUSE with multiple agents

### PR DESCRIPTION
**Pull request by LennartMorlock**
# Description

This commit includes the minor change to the _inner_split function in the demand_share.py file, described in the [related issue](https://github.com/EnergySystemsModellingLab/MUSE_OS/issues/252#issue-2179280270). 

It solves the error. However, uncertainty about its sensibility remains from a modelling perspective.

## Type of change

Please add a line in the relevant section of
[CHANGELOG.md](https://github.com/SGIModel/StarMuse/blob/development/CHANGELOG.md) to
document the change (include PR #) - note reverse order of PR #s.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (non-breaking, back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (whatever its nature)

## Key checklist

- [ ] All tests pass: `$ python -m pytest`
- [ ] The documentation builds and looks OK: `$ python -m sphinx -b html docs docs/build`

## Further checks

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Comment by martinstringer** [comment]
Hi Lennart, thank you from all of us for proposing this fix. If time allows, would you be able to also share your understanding of what your proposed changes are doing? If this could be added directly as comments to the new lines of code, even better.

**Comment by LennartMorlock** [comment]
Sorry for not responding earlier. I created a much-simplified model (attached) that causes the same error aimed to be solved with this pull request. I added it to the related issue as well. 

[simple_model_error.zip](https://github.com/EnergySystemsModellingLab/MUSE_OS/files/15306234/simple_model_error.zip)

**Comment by alexdewar** [comment]
Hi @LennartMorlock. Thanks for your reply. I was able to replicate the issue with the config files you attached.

I'm not sure what this function is supposed to be doing either tbh! It's a little opaque. I'm tagging my colleague @dalonsoa who might have a better idea.

**Comment by dalonsoa** [comment]
Not much to add to what is said in the docstring. The demand of any commodity needs to be split between the agents so they can use their share of the demand to invest in new technologies. Now, why there's an `unassigned`, why is calculated that way and its relationship with `total`, I don't really know.

**Comment by alexdewar** [comment]
Okey doke. I'll have a play with it a bit more to see if I can understand it better, but provided that it passes tests, would you be happy if this is merged?

**Comment by dalonsoa** [comment]
After updating the branch, yes, I think that's fine.

**Review by alexdewar — APPROVED** [review]
This looks godo to me @LennartMorlock. I wasn't entirely able to figure out what was happening with that `unassigned` variable, but your change seems sensible.

I've had a go at tidying it up a bit. I don't think we need to mention the old code in the comments. Also, I extracted the sum of the `shares` objects into its own variable for the sake of readability and not performing the calculation twice.

I've rerun it over your sample config and it seems to still produce the same result, but would you mind checking that what I've done makes sense to you, please? If you're happy with it I'll merge this branch.

**Comment by LennartMorlock** [comment]
Hi @alexdewar, 
yeah, the changes seem good to me. I still get the same results and the code definitely looks cleaner.

**Comment by alexdewar** [comment]
Great, thanks :smile:

**Pull request merged**
