### PR TITLE
Add codespell `pre-commit` hook

### PR DESCRIPTION
**Pull request by alexdewar**
# Description

As promised, here is a PR which adds the codespell `pre-commit` hook to check spelling in the code base and documentation and fixes up any errors found.

You can add words to be ignored to the `.codespell_ignore.txt` file. You can also ignore whole files with an extra argument to `codespell`, but I haven't needed to do that yet.

### CODE REVIEW

**Comment by tsmbland** [comment]
Not sure why the documentation build is failing, but I'm getting the same thing [here](https://github.com/EnergySystemsModellingLab/MUSE_OS/pull/279)

**Comment by alexdewar** [comment]
Weird... From the logs it doesn't look like it's something I've broken (phew!). I've set the job to re-run; hopefully it was just a fluke.

**Comment by dalonsoa** [comment]
Some flaky issue. Now it works after re-running the failing job.

**Review by dalonsoa — APPROVED** [review]
A much needed addition!!

**Pull request merged**
