### PR TITLE
Changes default solver to scipy

### PR DESCRIPTION
**Pull request by dalonsoa**
# Description

Sets the default solver to scipy, updating also the settings files.

Fixes # N/A

## Type of change

Please add a line in the relevant section of
[CHANGELOG.md](https://github.com/EnergySystemsModellingLab/MUSE_OS/blob/development/CHANGELOG.md) to
document the change (include PR #) - note reverse order of PR #s.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (non-breaking, back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Breaking change (whatever its nature)

## Key checklist

- [x] All tests pass: `$ python -m pytest`
- [x] The documentation builds and looks OK: `$ python -m sphinx -b html docs docs/build`

## Further checks

- [x] Code is commented, particularly in hard-to-understand areas
- [x] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Review by tsmbland — APPROVED** [review]

**Review by alexdewar — APPROVED** [review]
LGTM!

**Comment by tsmbland** [comment]
Shall we merge this?

**Comment by ahawkes** [comment]
I think we hold off on this for now. I think it will be a breaking (or at least disconcerting) change for some models (that use adhoc by default)

**Comment by dalonsoa** [comment]
I'm going to close this. We will revisit in the future if/when needed.

**Pull request closed without merging**
