### PR TITLE
Enable consumption data in `demand_path` format

### LINKED ISSUE #364: No longer compatible with consumption data in the `demand_path` format [BUG]
## Describe the bug

I tried running the model from #338 with the current dev version of MUSE, and faced a number of issues.

The first is an issue with how timeslices are defined in `settings.toml`. MUSE expects three levels for timeslice, but only two levels were defined for each of the timeslices in the file (e.g. `winter.night` should be `winter.all-week.night` etc). I'm not sure why this error is permitted in old versions of MUSE and not the dev version. This is a good thing and not a problem with MUSE, I'm just flagging this first as it's relevant for tacking this issue.

Anyway, when I fix this issue, the model still fails to run with the following error:

`ValueError: These variables cannot be found in this dataset: ['day', 'timeslice', 'month', 'hour']`

which relates to `drop` in line 118 of `preset_sectors.py`.

This seems to relate to the format that the consumption data takes in the input files. All the models we've been working with use the `consumption_path` format which includes timeslice data, however this model uses the `demand_path` format which doesn't include any timeslice data (see https://muse-os.readthedocs.io/en/latest/inputs/toml.html#preset-sectors)

I guess this is why it's complaining about trying to drop the timeslice variables, as these variables don't exist in the input data, but I'd have to dig into it a bit further to find the exact problem

## To Reproduce

Try running the model from #338, fixing the error in `settings.toml` that I described above 

## Expected behavior

The model should run without error

## Context

Please, complete the following to better understand the system you are using to run MUSE.

- Operating system (eg. Windows 10):
- MUSE version (eg. 1.0.1): dev
- Installation method (eg. pipx, pip, development mode): dev
- Python version (you can get this running `python --version`): 3.12

### PR DESCRIPTION
**Pull request by tsmbland**
# Description

This is a not very elegant way of getting Sharwari's model from #338 to work with the latest MUSE version. The problem was that she was specifying the demand data in a format that doesn't have timeslice information (the `demand_path` format, see [here](https://muse-os.readthedocs.io/en/latest/inputs/toml.html#preset-sectors)), which is a valid scenario and something that worked before, but something that we accidentally broke with (I think) #289.

Specifically, a couple of places in the code were complaining because it was trying to call `drop_vars(["timeslice", "month", "day", "hour"])` on xarrays that don't have timeslice data. Adding `errors="ignore"` means that it will try to drop these variables, and not raise a fuss if they already don't exist.

See also #381 which is also related to these `drop_vars` statements.

Ideally we'd have a test to make sure this doesn't break again, although I'm not sure the best way to do that without creating a new example model for the regressions tests, which seems a bit overkill. @dalonsoa - ideas?

Note also that Sharwari's model still fails due to #383 (although that one could be easily bypassed by removing the output)

Fixes #364 

## Type of change

Please add a line in the relevant section of
[CHANGELOG.md](https://github.com/EnergySystemsModellingLab/MUSE_OS/blob/development/CHANGELOG.md) to
document the change (include PR #) - note reverse order of PR #s.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (non-breaking, back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (whatever its nature)

## Key checklist

- [ ] All tests pass: `$ python -m pytest`
- [ ] The documentation builds and looks OK: `$ python -m sphinx -b html docs docs/build`

## Further checks

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Review by alexdewar — APPROVED** [review]
LGTM!

In terms of how we catch things like this in future, I agree that we probably don't want another example model, but it might still be useful to have @sharwaridixit's model be run as part of the regression tests, if it's using code paths that are otherwise untested. Would it be useful to have another set of models which are *just* used for those tests? Alternatively, I guess we could add a unit test or two.

**Comment by dalonsoa** [comment]
I think that, at this point, we might want to recover @alexdewar idea of a helper function to drop these. Something like:

```python
def drop_timeslice(data):
    if "timeslice" not in data.dims:
        return data

    return data.drop_vars([c for c in data.timeslice.indexes])
```

This would also be independent on the name of the timeslice levels. Normally they are `month`, `day`, `hour`, but that is just a convention. One could equally use `season`, `week`, `hour`.

**Comment by tsmbland** [comment]
Yes that's a good idea. I'll give that a try in #381

**Comment by tsmbland** [comment]
Opened #392 to deal with timeslice dropping. Just need this very small change as well to fix the issue

**Pull request merged**
