### PR TITLE
:sparkles: Add log to file.

### LINKED ISSUE #498: Output warnings to a file
Currently MUSE produces a few types of warnings when issues arise. These have important information that users need to pay attention to, but currently they get buried in the deluge of messages that MUSE prints so are likely to be ignored

I think warning messages should be outputted to a file so they're easier to see, and to keep a permanent record. To be honest it's probably a good idea to have some kind of log file anyway including information like the MUSE version and Python version, so warning messages can be a part of this

### PR DESCRIPTION
**Pull request by dalonsoa**
# Description

To make everyone's life easier when running and developing MUSE. Currently the tests also produce log files. This might or might not be desirable.

Fixes #498 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (non-breaking, back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (whatever its nature)

## Key checklist

- [x] All tests pass: `$ python -m pytest`
- [x] The documentation builds and looks OK: `$ python -m sphinx -b html docs docs/build`

## Further checks

- [x] Code is commented, particularly in hard-to-understand areas
- [x] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Comment by tsmbland** [comment]
Thanks for this!

A few comments/ideas (happy to open these as separate issues if you don't want to do this here):
- Is it possible to have two separate files: one for INFO statements and one for WARNING statements? I especially want users to pay more attention to warnings, so I think having these in a separate file would help.
- I would just call these `muse_info.log` and `muse_warning.log` by default (i.e. no date). Otherwise if you run the model many times you're going to get an accumulation of log files (maybe this is what you'll want in some circumstances, but I'd say not by default) 
- I think it probably makes more sense to put these files in the results folder by default (i.e. `default_output_dir`). This way it's clear which log files match up with which results files, which could otherwise get confusing if you're running multiple models from the same working directory

**Comment by dalonsoa** [comment]
No problem to do so now. And also to fix the tests, that I had forgotten that we support Python 3.9.

So, just to confirm, we don't give the option to select the log file name(s) just `muse_info` and `muse_warning`. I prefer that, simpler and cleaner, but just to be sure.

**Comment by tsmbland** [comment]
> No problem to do so now. And also to fix the tests, that I had forgotten that we support Python 3.9.
> 
> So, just to confirm, we don't give the option to select the log file name(s) just `muse_info` and `muse_warning`. I prefer that, simpler and cleaner, but just to be sure.

Cool. Yeah let's just keep it simple and hardcode the file names

**Comment by dalonsoa** [comment]
Done. I had to do some tweaking since tests were failing when running in parallel because they were all trying to access the same log file. I've disabled logging to file during tests, I think, since I could not find a way of indicating that using fixtures (all my attempts were ignored).

**Comment by dalonsoa** [comment]
I've no idea why building the docs fail. Certainly, running `muse --model default` works locally (at least in Windows) so I'm not sure why it might be failing there.

**Comment by tsmbland** [comment]
> I've no idea why building the docs fail. Certainly, running `muse --model default` works locally (at least in Windows) so I'm not sure why it might be failing there.

It's because the results folder doesn't exist yet when it tries to create the file (you'll already have a results folder locally from previous runs)

**Comment by dalonsoa** [comment]
@tsmbland , all good, now! Many thanks for the tip.

**Review by tsmbland — APPROVED** [review]
Great, all looks good! Thanks very much

**Pull request merged**
